In [17]:
DATA_PATH = "/content/drive/MyDrive/EmployeeAttrition/Employee_Dataset.csv"

In [18]:
import os
print(os.path.exists(DATA_PATH))

True

In [19]:
import pandas as pd

data = pd.read_csv(DATA_PATH)

data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [20]:
data.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [21]:
data.shape

(1470, 35)

In [22]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [23]:
data["Age"]

0       41
1       49
2       37
3       33
4       27
        ..
1465    36
1466    39
1467    27
1468    49
1469    34
Name: Age, Length: 1470, dtype: int64

In [24]:
data[["Age","Department"]]

      Age              Department
0      41                   Sales
1      49  Research & Development
2      37  Research & Development
3      33  Research & Development
4      27  Research & Development
...   ...                     ...
1465   36  Research & Development
1466   39  Research & Development
1467   27  Research & Development
1468   49                   Sales
1469   34  Research & Development

[1470 rows x 2 columns]

In [25]:
older_employees = data[data["Age"] > 40]

older_employees.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8

In [26]:
left_employees = data[data["Attrition"] == "Yes"]

print(left_employees.head())

    Age Attrition BusinessTravel  DailyRate              Department  \
0    41       Yes  Travel_Rarely       1102                   Sales
2    37       Yes  Travel_Rarely       1373  Research & Development
14   28       Yes  Travel_Rarely        103  Research & Development
21   36       Yes  Travel_Rarely       1218                   Sales
24   34       Yes  Travel_Rarely        699  Research & Development

    DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                  1          2  Life Sciences              1               1
2                  2          2          Other              1               4
14                24          3  Life Sciences              1              19
21                 9          4  Life Sciences              1              27
24                 6          1        Medical              1              31

    ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0   ...                         1            80                 0
2   ...                         2            80                 0
14  ...                         2            80                 0
21  ...                         2            80                 0
24  ...                         3            80                 0

    TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                   8                      0               1               6
2                   7                      3               3               0
14                  6                      4               3               4
21                 10                      4               3               5
24                  8                      2               3               4

   YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
0                   4                        0                     5
2                   0                        0                     0
14                  2                        0                     3
21                  3                        0                     3
24                  2                        1                     3

[5 rows x 35 columns]

In [27]:
print("Total employees:", len(data))

print("Employees who left:", len(data[data["Attrition"] == "Yes"]))

print("Employees who stayed:", len(data[data["Attrition"] == "No"]))

Total employees: 1470
Employees who left: 237
Employees who stayed: 1233

In [28]:
data[["Age", "Department", "JobRole", "MonthlyIncome", "Attrition"]].head(10)

,Age,Department,JobRole,MonthlyIncome,Attrition
0,41,Sales,Sales Executive,5993,Yes
1,49,Research & Development,Research Scientist,5130,No
2,37,Research & Development,Laboratory Technician,2090,Yes
3,33,Research & Development,Research Scientist,2909,No
4,27,Research & Development,Laboratory Technician,3468,No
5,32,Research & Development,Laboratory Technician,3068,No
6,59,Research & Development,Laboratory Technician,2670,No
7,30,Research & Development,Laboratory Technician,2693,No
8,38,Research & Development,Manufacturing Director,9526,No
9,36,Research & Development,Healthcare Representative,5237,No

In [29]:
data.sort_values("MonthlyIncome", ascending=False).head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
190,52,No,Travel_Rarely,699,Research & Development,1,4,Life Sciences,1,259,...,1,80,1,34,5,3,33,18,11,9
746,41,No,Non-Travel,247,Research & Development,7,1,Life Sciences,1,1035,...,2,80,2,21,3,3,21,16,5,10
851,56,No,Travel_Rarely,718,Research & Development,4,4,Technical Degree,1,1191,...,4,80,1,28,2,3,5,2,4,2
165,50,No,Travel_Rarely,1452,Research & Development,11,3,Life Sciences,1,226,...,2,80,0,21,5,3,5,4,4,4
568,55,Yes,Travel_Rarely,725,Research & Development,2,3,Medical,1,787,...,4,80,1,24,2,3,5,2,1,4
918,51,No,Travel_Frequently,237,Sales,9,3,Life Sciences,1,1282,...,1,80,1,31,5,2,29,10,11,10
749,52,Yes,Travel_Rarely,266,Sales,2,1,Marketing,1,1038,...,4,80,1,33,3,3,32,14,6,9
1242,40,No,Travel_Rarely,611,Sales,7,4,Medical,1,1740,...,2,80,0,21,3,2,21,8,12,8
898,43,No,Travel_Rarely,920,Research & Development,3,3,Life Sciences,1,1255,...,2,80,1,25,2,3,8,7,0,7
956,56,No,Travel_Rarely,206,Human Resources,8,4,Life Sciences,1,1338,...,1,80,0,36,4,3,7,3,7,7

In [30]:
data.groupby("Department")["MonthlyIncome"].mean()

Department
Human Resources           6654.507937
Research & Development    6281.252862
Sales                     6959.172646
Name: MonthlyIncome, dtype: float64

In [31]:
data.groupby("Department")["MonthlyIncome"].agg(
    ["mean", "min", "max"]
)

                               mean   min    max
Department
Human Resources         6654.507937  1555  19717
Research & Development  6281.252862  1009  19999
Sales                   6959.172646  1052  19847

In [32]:
data.groupby("Department").size()

Department
Human Resources            63
Research & Development    961
Sales                     446
dtype: int64

In [33]:
data.groupby("Department")["Attrition"].value_counts()

Department              Attrition
Human Resources         No            51
                        Yes           12
Research & Development  No           828
                        Yes          133
Sales                   No           354
                        Yes           92
Name: count, dtype: int64

In [34]:
data["Attrition_Flag"] = data["Attrition"].map({
    "Yes": 1,
    "No": 0
})

In [35]:
data[["Attrition", "Attrition_Flag"]].head(10)

  Attrition  Attrition_Flag
0       Yes               1
1        No               0
2       Yes               1
3        No               0
4        No               0
5        No               0
6        No               0
7        No               0
8        No               0
9        No               0

In [36]:
department_attrition = (
    data.groupby("Department")["Attrition_Flag"]
    .mean()
    * 100
)

print(department_attrition)

Department
Human Resources           19.047619
Research & Development    13.839750
Sales                     20.627803
Name: Attrition_Flag, dtype: float64

In [37]:
department_summary = data.groupby("Department").agg(
    Employees=("EmployeeNumber", "count"),
    AverageIncome=("MonthlyIncome", "mean"),
    AverageAge=("Age", "mean"),
    AttritionRate=("Attrition_Flag", "mean")
)

department_summary["AttritionRate"] = (
    department_summary["AttritionRate"] * 100
)

department_summary

                        Employees  AverageIncome  AverageAge  AttritionRate
Department
Human Resources                63    6654.507937   37.809524      19.047619
Research & Development        961    6281.252862   37.042664      13.839750
Sales                         446    6959.172646   36.542601      20.627803

In [38]:
data["JobRole"].value_counts()

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

In [39]:
jobrole_attrition = (
    data.groupby("JobRole")["Attrition_Flag"]
    .mean()
    * 100
)

print(jobrole_attrition)

JobRole
Healthcare Representative     6.870229
Human Resources              23.076923
Laboratory Technician        23.938224
Manager                       4.901961
Manufacturing Director        6.896552
Research Director             2.500000
Research Scientist           16.095890
Sales Executive              17.484663
Sales Representative         39.759036
Name: Attrition_Flag, dtype: float64

In [40]:
data["OverTime"].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [41]:
overtime_attrition = (
    data.groupby("OverTime")["Attrition_Flag"]
    .mean()
    * 100
)

print(overtime_attrition)

OverTime
No     10.436433
Yes    30.528846
Name: Attrition_Flag, dtype: float64

In [42]:
satisfaction_attrition = (
    data.groupby("JobSatisfaction")["Attrition_Flag"]
    .mean()
    * 100
)

print(satisfaction_attrition)

JobSatisfaction
1    22.837370
2    16.428571
3    16.515837
4    11.328976
Name: Attrition_Flag, dtype: float64

In [43]:
worklife_attrition = (
    data.groupby("WorkLifeBalance")["Attrition_Flag"]
    .mean()
    * 100
)

print(worklife_attrition)

WorkLifeBalance
1    31.250000
2    16.860465
3    14.221725
4    17.647059
Name: Attrition_Flag, dtype: float64

In [44]:
import os

reports_path = "/content/drive/MyDrive/EmployeeAttrition/reports"

os.makedirs(reports_path, exist_ok=True)

In [45]:
department_summary.to_csv(
    reports_path + "/department_summary.csv"
)

In [46]:
jobrole_attrition.to_csv(
    reports_path + "/jobrole_attrition.csv"
)

In [47]:
overtime_attrition.to_csv(
    reports_path + "/overtime_attrition.csv"
)

In [48]:
#What is the average MonthlyIncome for employees who left vs stayed?
data.groupby("Attrition")["MonthlyIncome"].mean()

Attrition
No     6832.739659
Yes    4787.092827
Name: MonthlyIncome, dtype: float64